### ISSUE TITLE
Set terrain type on draw and/or allow mass edit

### ISSUE THREAD

**Issue by JamzTheMan** [ironmonk88/enhanced-terrain-layer#13]
It would be nice if you could set the terrain environment/obstacles when you draw them.

Also, if you select multiple terrains, it would be great if you could edit them all at once (set the multiplier and/or environment)

**Comment by ironmonk88** [comment]
You can set the default environment using the scene config.
And you can edit multiple terrains using the HUD.  You can't using the config screen, but that's consistent with the rest of Foundry tools.

Changing the environment using the HUD is scheduled for next release.

**Comment by ironmonk88** [comment]
Next version has just released, you can now change environment type from the HUD.
