### ISSUE TITLE
HUD & UI not working as expected?

### ISSUE THREAD

**Issue by JamzTheMan** [ironmonk88/enhanced-terrain-layer#14]
Unless I'm missing something, I don't think the HUD is displaying the new Environment/Obstacles?  This is what I get with latest version...

Also, the UI for the Edit Dialog seems to be acting odd. When using Separate Obstacles, the Environment dropdown still shows the obstacles and when you select from the 'Obstacle' drop down, it populates it in the Environment drop down (so it's still combined)

![image](https://user-images.githubusercontent.com/8051654/116437925-8b4f3100-a813-11eb-87af-5c350089e014.png)

**Comment by ironmonk88** [comment]
That looks like it's working 100% correctly.

Separating the obstacles, doesn't mean removing them from the environment list.  It means that you can have an environment in combination with an obstacle.  It's meant for having things like Arctic Rubble.  So if you have a character that ignores difficult terrain in an Arctic environment, it can ignore that terrain.  Or if you have a character that ignores Rubble, it can ignore that terrain.  Whereas if it was two sets of difficult terrain, both those characters would be caught in difficult terrain.

This does not exclude there being terrain set just as Arctic.  Or setting Terrain that's just Rubble.

The feature is only for using Environment and Obstacle together.  So if you try and set just the obstacle with no Environment, then ultimately you are just calling that Terrain as the Obstacle.

I'll update the wording to see if it makes more sense.
