### ISSUE TITLE
Enhanced Terrain Layer Throws Error When Opening Items. [PF2e]

### ISSUE THREAD

**Issue by velara** [ironmonk88/enhanced-terrain-layer#16]
![image](https://user-images.githubusercontent.com/74130268/116449137-167df600-a817-11eb-95d3-1f8966b70372.png)

I get the following error when I open any feat or effect items in my item directory with enhanced terrain layer active. 
The error persists even when I disable all other modules. 

This occurs while running PF2e, and only began with the latest update.

**Comment by ironmonk88** [comment]
Knew I'd miss something.
Should be fixed now, new version has been released.
Thanks for catching that.
