### ISSUE TITLE
Incompatibility with Token Magic

### ISSUE THREAD

**Issue by vanderleitelesjr** [ironmonk88/enhanced-terrain-layer#17]
libWrapper is accusing an incomaptibility between Enhanced Terrain Layer and Token Magic on the usage of:
gme.dnd5e.canvas.AbilityTemplate.fromItem

Is this something that will cause issues or are they using different methods?

**Comment by Merudo** [comment]
I get the following error message from the console:

```
libWrapper: Potential conflict detected between module 'enhanced-terrain-layer' and 'tokenmagic'.
Detected non-libWrapper wrapping of 'game.dnd5e.canvas.AbilityTemplate.fromItem' by 'enhanced-terrain-layer'. This will potentially lead to conflicts.
🎁console_ui @ libWrapper-consts.js:8
```

**Comment by ironmonk88** [comment]
It shouldn't cause an issue.  Terrain Layer was just wrapping.
But I did change the code to support libWrapper.
