### ISSUE TITLE
Option to Ignore by Terrain Type, independently from elevation.

### ISSUE THREAD

**Issue by velara** [ironmonk88/enhanced-terrain-layer#2]
It looks like you've included functionality where we can feed options into the cost function allowing us to ignore difficult terrain based on the selected environment. Which appears to be handled using: !options.ignore?.includes(terrain.environment) generally and options.ignore?.includes(measEnv) for templates.

However as far as terrain type goes, (ground, air, ground & air) the only option appears to be to give the cost function the tokens elevation and let it handle things from there.

In some use cases it would be nice to be able to tell the cost function to ignore ground terrain or air terrain without linking it to elevation. For example, for a token where elevation is used to indicate being on top of a cliff, we may want the token to ignore air difficult terrain but respect ground difficult terrain.

If you add a line to check for !options.ignore?.includes(terrain.terraintype) and !options.ignore?.includes(measType) it'll be easy to handle those sorts of cases in modules that are calling the cost function.

Though it would likely require some additional code to override the elevation related changes if the ignore list includes a terrain type.

**Comment by manuelVo** [comment]
Another option that I could think of for handling this is returning detailed info about the causes of difficult terrain (and what cost that terrain would inccur) and leaving the job of figuring out how much cost to actually apply to the module requesting that information. That would also allow for more complex, game system specific implementations. I could imagine that some game systems charge different costs if there are multiple sources of difficulty at once. Like walking through an occupied square on a stair. The stair itself could be difficult and walking through another creature's square could be difficult as well. Some game system may charge difficult terrain twice, while some may only do it once or only charge the more expensive of the two. Doing game system specific handling for every system out there might be a lot of work, so leaving it up to other people to do is probably the easier route for you to go.

**Comment by vanderleitelesjr** [comment]
Or you could replace the Ground/Air/Ground & Air flags with numeric values and set the penalty to be ignored if the token height is above the set threshold, this way flying tokens or tokens that are on a higher elevation and are simply dropping to the lower elevation won't get penalized.

**Comment by ironmonk88** [comment]
That's 100% where I'm going with that, when I get the time.  Setting the terrain height I think should solve a lot of issues.  I'm working on providing a range element with two sliders on it, so you can use the upper and lower limits of the affected area.

**Comment by ironmonk88** [comment]
Terrain height is active now.
Makes more sense than the old terrain type.
This should cover this issue, as it will check to make sure a token's elevation is within the terrain's range.
