### ISSUE TITLE
Environment Selection Menu Broken.

### ISSUE THREAD

**Issue by velara** [ironmonk88/enhanced-terrain-layer#3]
![image](https://user-images.githubusercontent.com/74130268/112769813-58c9d280-8fe0-11eb-95b3-cc769f376dc3.png)

The issue is an omitted word on line 50 of terrainlayer.js

  static environment() {  when it needs to be   **static get environment() {**

After this change the menu functions normally. 
![image](https://user-images.githubusercontent.com/74130268/112769851-96c6f680-8fe0-11eb-8438-3a841d7d2505.png)

**Comment by ironmonk88** [comment]
Thanks for finding that.
I changed it from being a get to a function so people could override it easier.
updated the export function in terrainlayer.js to reflect that it's now a function.
Should be available in 1.0.14.
