### ISSUE TITLE
Newly created areas of terrain don't effect ruler until tweaked

### ISSUE THREAD

**Issue by DuskyVoltage** [ironmonk88/enhanced-terrain-layer#6]
I'm finding the error doesn't always occur, and I'm not sure what may be triggering it.
Using Drag Ruler + Enhanced Terrain Layer + Terrain Ruler

When creating a new area of difficult terrain, it does not affect tokens moving through it until the area is changed in some way (Such as going 3x then back to 2x, or changing the environment, etc).
After it's tweaked it works fine.

Sometimes when I start the server it performs this behaviour. Sometimes when I start the server it works fine out of the gate.

**Comment by ironmonk88** [comment]
Is there a message in the console log that costGrid is deprecated?
If there is, then it's because I'm trying to provide some backwards compatibility... but the previous method used really isn't compatible with how I'm currently doing it.
Most of the newer generation of rulers are going to start using the cost() function which provides a much better result.  And will avoid this error.

**Comment by miguel-pinto-prodmad** [comment]
I'm having the same issue but in my case it's doesn't start working regardless of changing the cost.
I don't see any errors on the console.
![image](https://user-images.githubusercontent.com/15193682/114219906-354d4300-9963-11eb-8e81-0a8cd6a8a3ac.png)

I'm on
- **Core** 0.7.9
- **DnD 5e** 1.2.4

**Comment by ironmonk88** [comment]
What ruler are you using?  Enhanced Terrain Layer is just a library and won't do anything other than record terrain.
For it to calculate difficult terrain you need to use one of the ruler modules that integrates with Enhanced Terrain Layer.

**Comment by miguel-pinto-prodmad** [comment]
My understanding was that this module would reflect when the rule/measure is used it would already take into account the additional terrain in the measure (ex: if I measure 5ft into a difficult terrain layer of x2, then the rule would show 10ft instead.

But if this is not how the module work, it's fine. Maybe it was just my incorrect perception.

**Comment by nulmas** [comment]
> My understanding was that this module would reflect when the rule/measure is used it would already take into account the additional terrain in the measure (ex: if I measure 5ft into a difficult terrain layer of x2, then the rule would show 10ft instead.)
> 
> So in my example above, I was expecting the measure rule to show 25ft.
> 
> But if this is not how the module work, it's fine. Maybe it was just my incorrect perception.

You need to be using an additional module (like Terrain Ruler or Drag Ruler, or both) for it to work.

**Comment by ironmonk88** [comment]
Closing this ticket because I think it's solved.
Enhanced Terrain Layer doesn't calculate the cost.  Only stores information.  The rulers calculate the cost.
Drag Ruler and Terrain Ruler are using the new cost function so they should both be working correctly.
