### ISSUE TITLE
hidden terrain is not counted/calculated

### ISSUE THREAD

**Issue by zarmstrong** [ironmonk88/enhanced-terrain-layer#8]
I am using foundryvtt-drag-ruler and pf2edragruler.  If I mark the terrain as hidden, the difficult terrain does not work on the drag ruler.  Am I missing something here?  Also not sure which module is the cause of this.

**Comment by ironmonk88** [comment]
That's the point of hiding it.
It's meant to be for conditional terrain, such as a landslide that hasn't happened yet, or a trap that hasn't been triggered.  While hidden it's not active yet, and as soon as it become visible then it's actually part of the terrain and counts.

If you'd prefer the terrain to never highlight when you drag your mouse... that's a different question.  And currently hasn't been added to Enhanced Terrain, but could be.

**Comment by zarmstrong** [comment]
Gotcha, that makes sense.  Then I guess another thing would be to make the difficult terrain less visible. It's almost impossible to see the map underneath -- that's why i was turning on hidden. Would be nice to have both options -- to hide it yet be active, and to hide and and be inactive

**Comment by ironmonk88** [comment]
I think I figured out the issue.  The opacity isn't working correctly.  Should be fixed in the latest release.
In the module configuration you're supposed to be able to set how visible the difficult terrain is.  It was ignoring that and always using the max.  You can now adjust that.

**Comment by zarmstrong** [comment]
Ahh yes that makes sense. I totally forgot about that slider. I definitely should have noted that it didn't seem to have any effect. My fault there.

Thanks for the troubleshooting/fix. You're doing great work!
