### ISSUE TITLE
[Enhancement] Treat other tokens differently depending on whether they are friendly/neutral/hostile

### ISSUE THREAD

**Issue by Doresain** [ironmonk88/enhanced-terrain-layer#9]
I don't know how this might apply to other rulesets, but for 5e at least:
`You can move through a nonhostile creature's space. In contrast, you can move through a hostile creature's space only if the creature is at least two sizes larger or smaller than you. Remember that another creature's space is difficult terrain for you.`

Would be killer if the module could check the disposition and help rulers make the difficult terrain/blocks movement distinction. 

No idea how best to implement this, as I'm not familiar enough with what is being passed, but the more I think about this the more I think it probably requires changes changes in the ruler as well, since you'd need to know the disposition of both the token being moved and the token being crossed:

- If moving token is FRIENDLY and crossed token is
-- FRIENDLY, difficult terrain
-- NEUTRAL, difficult terrain
-- HOSTILE, movement blocked (ruler turns red)
- If moving token is HOSTILE and crossed token is
-- FRIENDLY, movement blocked
-- NEUTRAL, difficult terrain
-- HOSTILE, difficult terrain
- If moving token is NEUTRAL, any crossed token is difficult terrain
- If you wanted to be really fancy, there's be some comparison between token actor sizes as well given the 'two sizes larger or smaller' rule.

**Comment by ironmonk88** [comment]
I think this would sit with the ruler.  And I agree with Manuel Vögele that this should be implemented in a system specific ruler.
Enhanced Terrain Layer already passes the information about what tokens it encounters when calculating the cost.
And since the cost is correct, I'm closing the ticket.
I like the idea, but blocking the movement or implementing system specific rules is more about the ruler than the terrain layer.

**Comment by Doresain** [comment]
Yep, this makes sense to me. If you're already passing token information that a downstream module could use to compare tokens and do whatever logic needs doing that seems like the only obligation of the terrain layer. 👍
